---
- hosts: localhost

  vars:
    gcp:
      driver: google
      hostname: "{{ hostname }}"
      #machine_image: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1404-trusty-v20161109
      machine_image: https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20161115
      machine_type: n1-standard-1
      project: ood2016-handson
      zone: asia-northeast1-a
 
  tasks:
  - command: >
      docker-machine create
      --driver "{{ gcp.driver }}"
      --google-project "{{ gcp.project }}"
      --google-zone "{{ gcp.zone }}"
      --google-machine-type "{{ gcp.machine_type }}"
      --google-machine-image "{{ gcp.machine_image }}"
      "{{ gcp.hostname }}"
    #async: 1
    #poll: 0
  - command: >
      gcloud compute ssh "{{ gcp.hostname }}"
      --zone "{{ gcp.zone }}" -- uname
  - name: show getting start
    debug:
      msg: "Usage: ssh -i <private-key file> -l {{ ansible_user_id }} {{ gcp.hostname }}.{{ gcp.zone }}.{{ gcp.project }}"
    tags:
      - usage
